//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeEndanceAndDeparture = new HashSet<EmployeEndanceAndDeparture>();
            this.EmployeeSetting = new HashSet<EmployeeSetting>();
            this.EmployeeSalary = new HashSet<EmployeeSalary>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string Nationality { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string NationalityNumber { get; set; }
        public Nullable<System.DateTime> DateofContract { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> Attendance { get; set; }
        public Nullable<System.DateTime> Departure { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeEndanceAndDeparture> EmployeEndanceAndDeparture { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSetting> EmployeeSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeSalary> EmployeeSalary { get; set; }
    }
}
