//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSalary
    {
        public int Id { get; set; }
        public string Section { get; set; }
        public Nullable<int> Presence { get; set; }
        public Nullable<int> absence { get; set; }
        public Nullable<int> ExtraHours { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> ExtraTotal { get; set; }
        public Nullable<int> ExtraDiscount { get; set; }
        public Nullable<int> Net { get; set; }
        public Nullable<int> Emp_Id { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
