//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeSetting
    {
        public int Id { get; set; }
        public Nullable<int> Attendance { get; set; }
        public Nullable<int> Departure { get; set; }
        public string Vaction1 { get; set; }
        public string Vaction2 { get; set; }
        public Nullable<int> EmpId { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
