//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication77.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usergroup
    {
        public int Id { get; set; }
        public string Page { get; set; }
        public Nullable<bool> Insert { get; set; }
        public Nullable<bool> Select { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
    }
}
